name: Matrices multiplication and test siut

on: [push, pull_request]

jobs:
  try:
    runs-on: ubuntu-latest

    steps:
    - name: Check code in actions
      uses: actions/checkout@v4

    - name: Set up c++
      run: sudo apt-get install g++

    - name: Compile c++
      run: g++ -o Matrices_multiplication Matrices_multiplication.cpp

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'

    - name: Run Python tests
      run: python test_suit.py
